from flask import Flask, render_template, request, redirect
import sqlite3
from flask import send_file
from reportlab.pdfgen import canvas
import matplotlib.pyplot as plt
from openpyxl import Workbook
from flask import send_file

app = Flask(__name__)
def create_database():

    conn = sqlite3.connect("internverify.db")

    cursor = conn.cursor()

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS internships(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        company TEXT,
        risk INTEGER,
        trust_score INTEGER,
        status TEXT
    )
    """)

    conn.commit()
    conn.close()

@app.route('/')
def home():
    return render_template("index.html")

@app.route('/check', methods=['POST'])
def check():

    company = request.form['company']
    stipend = int(request.form['stipend'])
    fee = int(request.form['fee'])
    website = request.form['website']
    email = request.form['email']

    risk = 0

    if fee > 0:
        risk += 20

    if website == "No":
        risk += 20

    if email == "No":
        risk += 10

    if stipend > 30000:
        risk += 20

    if risk >= 50:
        status = "High Risk"
    elif risk >= 20:
        status = "Moderate Risk"
    else:
        status = "Safe"
    trust_score = 100 - risk
    scam_probability = risk

    if risk >= 50:
       recommendation = "Avoid Applying"
    elif risk >= 20:
       recommendation = "Verify Before Applying"
    else:
       recommendation = "Safe to Apply"

    conn = sqlite3.connect("internverify.db")

    cursor = conn.cursor()

    cursor.execute("""
    INSERT INTO internships(company, risk, trust_score, status)
    VALUES (?, ?, ?, ?)
    """, (company, risk, trust_score, status))

    conn.commit()
    conn.close()

    return render_template(
    "result.html",
    company=company,
    risk=risk,
    status=status,
    trust_score=trust_score,
    scam_probability=scam_probability,
    recommendation=recommendation
)

@app.route('/history')
def history():

    search = request.args.get('search')

    conn = sqlite3.connect("internverify.db")
    cursor = conn.cursor()

    if search:
        cursor.execute("""
        SELECT company, risk, trust_score, status
        FROM internships
        WHERE company LIKE ?
        ORDER BY id DESC
        """, ('%' + search + '%',))
    else:
        cursor.execute("""
        SELECT company, risk, trust_score, status
        FROM internships
        ORDER BY id DESC
        """)

    records = cursor.fetchall()

    conn.close()

    return render_template("history.html", records=records)

@app.route('/dashboard')
def dashboard():

    conn = sqlite3.connect("internverify.db")

    cursor = conn.cursor()

    cursor.execute("SELECT COUNT(*) FROM internships")
    total = cursor.fetchone()[0]

    cursor.execute("SELECT COUNT(*) FROM internships WHERE status='High Risk'")
    high_risk = cursor.fetchone()[0]

    cursor.execute("SELECT COUNT(*) FROM internships WHERE status='Moderate Risk'")
    moderate_risk = cursor.fetchone()[0]

    cursor.execute("SELECT COUNT(*) FROM internships WHERE status='Safe'")
    safe = cursor.fetchone()[0]

    labels = ['High Risk', 'Moderate Risk', 'Safe']
    values = [high_risk, moderate_risk, safe]

    if sum(values) > 0:
       plt.figure(figsize=(5,5))
       plt.pie(values, labels=labels, autopct='%1.1f%%')
       plt.title("Internship Risk Distribution")
       plt.savefig("static/chart.png", bbox_inches="tight")
       plt.close()

    conn.close()



    return render_template(
        "dashboard.html",
        total=total,
        high_risk=high_risk,
        moderate_risk=moderate_risk,
        safe=safe
    )

@app.route('/clear_history')
def clear_history():

    conn = sqlite3.connect("internverify.db")

    cursor = conn.cursor()

    cursor.execute("DELETE FROM internships")

    conn.commit()
    conn.close()

    return redirect('/history')

@app.route('/download_report')
def download_report():

    pdf_file = "report.pdf"

    c = canvas.Canvas(pdf_file)

    c.setFont("Helvetica-Bold", 18)
    c.drawString(180, 800, "InternVerify Report")

    c.setFont("Helvetica", 12)
    c.drawString(100, 750, "Internship Analysis Completed Successfully")

    c.drawString(100, 720, "Generated by InternVerify Platform")

    c.save()

    return send_file(pdf_file, as_attachment=True)

@app.route('/download_excel')
def download_excel():

    conn = sqlite3.connect("internverify.db")
    cursor = conn.cursor()

    cursor.execute("""
    SELECT company, risk, trust_score, status
    FROM internships
    """)

    records = cursor.fetchall()

    conn.close()

    wb = Workbook()
    ws = wb.active

    ws.title = "Internship History"

    ws.append(["Company", "Risk Score", "Trust Score", "Status"])

    for row in records:
        ws.append(row)

    file_name = "internverify_history.xlsx"
    wb.save(file_name)

    return send_file(file_name, as_attachment=True)

if __name__ == "__main__":
    create_database()
    app.run(debug=True)